services:
  - type: web
    name: temp-email-auth-service
    plan: free
    env: docker
    dockerContext: backend
    dockerfilePath: backend/auth-service/Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_USERNAME
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

  - type: web
    name: temp-email-gateway
    plan: free
    env: docker
    dockerContext: backend
    dockerfilePath: backend/gateway/Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: AUTH_SERVICE_URL
        fromService:
          name: temp-email-auth-service
          type: web
          property: hostport
      - key: MAIL_SERVICE_URL
        value: 0.0.0.0:0
      - key: MAILBOX_SERVICE_URL
        value: 0.0.0.0:0
      - key: PAYMENT_SERVICE_URL
        value: 0.0.0.0:0
      - key: CORS_ORIGIN
        sync: false
