services:
  - type: web
    name: temp-email-auth-service
    plan: free
    env: docker
    dockerContext: backend
    dockerfilePath: backend/auth-service/Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_USERNAME
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: NEW_RELIC_LICENSE_KEY
        sync: false
      - key: NEW_RELIC_APP_NAME
        sync: false

  - type: web
    name: temp-email-gateway
    plan: free
    env: docker
    dockerContext: backend
    dockerfilePath: backend/gateway/Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 50
      - key: AUTH_SERVICE_URL
        fromService:
          name: temp-email-auth-service
          type: web
          property: hostport
      - key: MAIL_SERVICE_URL
        value: 0.0.0.0:0
      - key: MAILBOX_SERVICE_URL
        value: 0.0.0.0:0
      - key: PAYMENT_SERVICE_URL
        value: 0.0.0.0:0
      - key: CORS_ORIGIN
        sync: false
      - key: NEW_RELIC_LICENSE_KEY
        sync: false
      - key: NEW_RELIC_APP_NAME
        sync: false
